< 판다스 DataFrame 타입(2차원 배열) 정보확인 >

DataFrame
• 표와 같은 스프레드시트 형식의 자료구조
• NumPy에 비유 하면 2차원 array   
• 색인의 모양이 같은 Series 객체를 담고 있는 파이썬 딕셔너리라고 생각해도 무방
• 서로 다른 종류의값(숫자, 문자열, 불리언등)을 담을 수 있는 여러칼럼을 가질 수 있다
(2차원 array는 동일한 데이터타입을 가져야 하지만, DataFrame은 열마다 다른 타입)

1. DataFrame 

- DataFrame클래스 생성자
pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)

DataFrame생성자의 data 매개값으로 자주 사용하는 데이터 타입
• 2차원ndarray
• 배열, 리스트, 사전
• Series 사전
• 다른DataFrame

In [1]:
# 2. DataFrame 정보 확인

import pandas as pd

In [ ]:
df = pd.DataFrame(
    [[90, 80],
     [70, 60]],
    columns=['국어', '영어']
)

df

   국어  영어
0  90  80
1  70  60

In [ ]:
# index값 행레이블(레이블 인덱스), columns 값 열레이블(레이블 인덱스)
# 생략하면 위치값으로 기본값이 설정된다.

df2 = pd.DataFrame([
            ["민수", 90], # 1행
            ["지영", 80]  # 2행

], index = ["첫번째", "두번째"], columns = ["이름", "점수"])

df2

     이름  점수
첫번째  민수  90
두번째  지영  80

In [ ]:
df3 = pd.DataFrame([
    {"이름" : "민수", "점수" : 90}, # 1행
    {"이름" : "지영", "점수" : 100} # 2행
])

df3

   이름   점수
0  민수   90
1  지영  100

In [ ]:
import numpy as np

# numpy의 2차원 배열 - 모든 데이터 타입이 동일
df4 = pd.DataFrame(np.array([
    [1 , 2],
    [3 , 4]
]))

df4

   0  1
0  1  2
1  3  4

In [11]:
# 이름, 나이, 성별 데이터로 DataFrame 생성
df = pd.DataFrame({
    '이름': ['철수', '영희', '민수', '지영', '준호'],
    '나이': [20, 21, 20, 22, 21],
    '성별': ['남', '여', '남', '여', '남']
})

df

   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남

In [12]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [14]:
df.columns

Index(['이름', '나이', '성별'], dtype='str')

In [ ]:
df.values # numpy의 array값으로 변환

array([['철수', 20, '남'],
       ['영희', 21, '여'],
       ['민수', 20, '남'],
       ['지영', 22, '여'],
       ['준호', 21, '남']], dtype=object)

In [15]:
df.dtypes # 반환값 시리즈타입 index =

이름      str
나이    int64
성별      str
dtype: object

In [16]:
# 1) info() 메서드
# 행 개수, 열 개수, 열 이름, 결측값이 아닌 데이터 개수, 데이터 타입 확인

print("===== info =====")
# DataFrame의 전체 정보를 출력
df.info()

===== info =====
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      str
 1   나이      5 non-null      int64
 2   성별      5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [17]:
# 2) shape : 행과 열의 크기

print("shape:", df.shape) # 출력 (행 개수, 열 개수)

print("행 개수:", df.shape[0])
print("열 개수:", df.shape[1])

shape: (5, 3)
행 개수: 5
열 개수: 3

In [18]:
# 3) dtypes : 각 열의 데이터 타입

print("===== dtypes =====")
print(df.dtypes)

# 특정 열의 데이터 타입 확인
print(df['나이'].dtype)
print(df['이름'].dtype)

===== dtypes =====
이름      str
나이    int64
성별      str
dtype: object
int64
str

In [19]:
# 4) columns : 열 이름 확인

print("===== columns =====")
print(df.columns)

# 이름만 확인
print(df.columns.tolist())

# in 연산자를 사용하여 특정 열의 존재 유무 확인
print('나이' in df.columns)
print('주소' in df.columns)

===== columns =====
Index(['이름', '나이', '성별'], dtype='str')
['이름', '나이', '성별']
True
False

In [20]:
# 5) index : 행 레이블 인덱스 확인(위치값 인덱스 아님)

print("===== index =====")
print(df.index)

===== index =====
RangeIndex(start=0, stop=5, step=1)

In [21]:
# 6) head, tail

print("===== head =====")
print(df.head()) # 기본값으로 5행
print(df.head(3))

print("===== tail =====")
print(df.tail())
print(df.tail(3))

===== head =====
   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남
   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
===== tail =====
   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남
   이름  나이 성별
2  민수  20  남
3  지영  22  여
4  준호  21  남

In [ ]:
# 7) unique, nunique : 고유값 확인, 고유값 개수

print(df['성별'].unique())
print(df['나이'].unique())

# 고유값 개수
print(df['성별'].nunique())