< 판다스 DataFrame타입의 iloc[]인덱스 vs loc[]인덱스 vs []인덱싱 연산자 >

                행선택          열선택
- loc[]         레이블          레이블 
- iloc[]       숫자 위치        숫자 위치
- df[]      조건/슬라이스 등     열 이름

1) 행과 열을 동시에 선택
loc[]   인덱스 → 레이블 기준으로 행/열 선택
iloc[]  인덱스 → 숫자 위치 기준으로 행/열 선택

2) 행, 열 중 하나만 선택
df[]    연산자 → 기본적으로 열 선택
                 조건식 → 행 선택 : 행을 선택하면 → 열은 전체
                 슬라이싱 → 행 선택 : 열을 선택하면 → 행은 전체
-> df[]는 기본적으로 한 축만 선택하고, 선택하지 않은 축은 전체이다.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최수진', '정우진'],
    '학년': [1, 2, 1, 3, 2],
    '점수': [85, 92, 78, 95, 88]
}, index=['A', 'B', 'C', 'D', 'E'])

df

# - 행 레이블 인덱스 → A, B, C, D, E
# - 행 위치 → 0, 1, 2, 3, 4

​# - 열 이름 → 이름, 학년, 점수
# - 열 위치 → 0, 1, 2

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

In [4]:
# 1. 행+열 선택

#1) loc인덱스 : 행 인덱스, 열이름 사용

# loc[행 인덱스, 열 이름]
print(df.loc['B', '점수']) # 92

# 여러행, 여러 열 선택 시 []안에 리스트 사용
print(df.loc[['B', 'D'], ['이름', '점수']])

#     이름  점수
# B  이영희   92
# D  최수진   95

92
    이름  점수
B  이영희  92
D  최수진  95

In [5]:
# loc[행 인덱스 슬라이싱, 열 이름 슬라이싱]
df.loc['B':'D', '이름':'학년']

    이름  학년
B  이영희   2
C  박민수   1
D  최수진   3

In [6]:
# 2) iloc인덱스 : 행 위치, 열 위치 사용

# iloc[행 위치, 열 위치]
print(df.iloc[1, 2]) # 92

# 여러행, 여려열 선택
print(df.iloc[[1, 3], [0, 2]])

92
    이름  점수
B  이영희  92
D  최수진  95

In [7]:
# iloc[행 위치 슬라이싱, 열 위치 슬라이싱]
df.iloc[1:4, 0:2]

    이름  학년
B  이영희   2
C  박민수   1
D  최수진   3

In [8]:
# 2. 열 선택

# 1) df[숫자]
# "열 이름이 0인 열"

#0번째 열 아님. 0번째 열은 iloc[]인덱스를 사용하여야 한다
df[0] # error

KeyError: 0

In [10]:
# 2) df['이름']

# 열 이름 위치
df['이름']

# 두개이상의 열은 []안에 리스트를 사용
df[['이름', '점수']]
# df["이름", "점수"] error! []연산자 안에는 하나의 표현식만이 올 수 있다

    이름  점수
A  김철수  85
B  이영희  92
C  박민수  78
D  최수진  95
E  정우진  88

[]연산자안에 매개값으로 리스트 타입이 입력되면 반환되는 타입은 하나 이상의 열을 반환하므로 DataFrame타입을 반환한다. []연산자안에 스칼라 열이 입력되면 반환타입은 Series타입을 반환.

df['점수']          # Series
df[['이름', '점수']]        # DataFrame

# 하나의 열이지만 리스트형태로 입력되면 반환타입은 1열짜리 DataFram타입이 반환된다.
df[['점수']]        # DataFrame

In [11]:
# 3. 행 선택

#1) df[슬라이싱] : []연산자안에 슬라이싱 표현식

df[1:4] # 행을 위치 기준으로 위치 1부터 3까지 선택

    이름  학년  점수
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95

In [12]:
# 2) df[열조건] : []연산자안에 열조건 표현식

df[df['점수'] >= 90] # 조건에 맞는 행 선택

    이름  학년  점수
B  이영희   2  92
D  최수진   3  95