< 판다스 DataFrame 입력, 수정, 삭제와 통계관련 메서드 >

In [1]:
# 1. 입력, 수정, 삭제

import pandas as pd

df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최수진', '정우진'],
    '학년': [1, 2, 1, 3, 2],
    '점수': [85, 92, 78, 95, 88],
    '출석': [90, 95, 80, 98, 85]
})

df

    이름  학년  점수  출석
0  김철수   1  85  90
1  이영희   2  92  95
2  박민수   1  78  80
3  최수진   3  95  98
4  정우진   2  88  85

In [2]:
# 새로운 열 추가

df['성적'] = ['B', 'A', 'C', 'A+', 'B+']

df

    이름  학년  점수  출석  성적
0  김철수   1  85  90   B
1  이영희   2  92  95   A
2  박민수   1  78  80   C
3  최수진   3  95  98  A+
4  정우진   2  88  85  B+

In [3]:
# 계산해서 새로운 열 만들기

df['총점'] = df['점수'] + df['출석']

df

    이름  학년  점수  출석  성적   총점
0  김철수   1  85  90   B  175
1  이영희   2  92  95   A  187
2  박민수   1  78  80   C  158
3  최수진   3  95  98  A+  193
4  정우진   2  88  85  B+  173

In [4]:
# 특정 값 수정

df.loc[0, '점수'] = 90

df

    이름  학년  점수  출석  성적   총점
0  김철수   1  90  90   B  175
1  이영희   2  92  95   A  187
2  박민수   1  78  80   C  158
3  최수진   3  95  98  A+  193
4  정우진   2  88  85  B+  173

In [5]:
df.loc[df['점수'] < 80, '점수'] = 80

df

    이름  학년  점수  출석  성적   총점
0  김철수   1  90  90   B  175
1  이영희   2  92  95   A  187
2  박민수   1  80  80   C  158
3  최수진   3  95  98  A+  193
4  정우진   2  88  85  B+  173

삭제 drop(열이름 or 레이블 인덱스)메서드

* drop()에 매개값으로 위치값을 사용할 수 없다
- 특정 위치 값들을 삭제 X -> 값을 공백, NaN, ... , 결측치 변경 O
​- 행들을 선택해서 삭제 - 세로축으로 선택 : axis = 0 행
- 열들을 선택해서 삭제 - 가로축으로 선택 : axis = 1 열

In [6]:
df = df.drop(0, axis=0) # axis는 생략하면 0

df

    이름  학년  점수  출석  성적   총점
1  이영희   2  92  95   A  187
2  박민수   1  80  80   C  158
3  최수진   3  95  98  A+  193
4  정우진   2  88  85  B+  173

In [7]:
# - 열삭제 : drop('열 레이블', axis=1)
# - axis=1은 열축(가로방향 - 하나이상의 열을 삭제 가능)
# '총점'을 열 방향(axis=1)에서 삭제

df.drop('총점', axis=1) # axis는 생략하면 0

df

    이름  학년  점수  출석  성적   총점
1  이영희   2  92  95   A  187
2  박민수   1  80  80   C  158
3  최수진   3  95  98  A+  193
4  정우진   2  88  85  B+  173

In [8]:
# 정보 확인

print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)

(4, 6)
Index(['이름', '학년', '점수', '출석', '성적', '총점'], dtype='str')
RangeIndex(start=1, stop=5, step=1)
이름      str
학년    int64
점수    int64
출석    int64
성적      str
총점    int64
dtype: object